const productos  = [
    {   id: 28,
        nombre: "Camisa Cuadro", 
        precio: 25,
        img: "/imgRebajas/rebaja9.png",
        cantidad: 1,
    },
    {
        id: 21,
        nombre: "Camisa Cuadros",
        precio: 33,
        img: "/imgRebajas/rebaja2.png",
        cantidad: 1,
    
    },
    {   id: 26,
        nombre: "Zapato mujer", 
        precio: 34,
        img: "/imgRebajas/rebaja7.png",
        cantidad: 1,
    },
    {   id: 22,
        nombre: "Jersey Margarita", 
        precio: 12,
        img: "/imgRebajas/rebaja3.png",
        cantidad: 1,
    },
    {
        id: 23,
        nombre: "Pantalón Pana",
        precio: 16,
        img: "/imgRebajas/rebaja4.png",
        cantidad: 1,
    
    },
    {   id: 24,
        nombre: "Zapatos Piel", 
        precio: 33,
        img: "/imgRebajas/rebaja5.png",
        cantidad: 1,
    },
    {
        id: 25,
        nombre: "Chupa Cuero",
        precio: 29,
        img: "/imgRebajas/rebaja6.png",
        cantidad: 1,
    
    },
    {   id: 20,
        nombre: "Vestido Lunares", 
        precio: 18,
        img: "/imgRebajas/rebaja1.png",
        cantidad: 1,
    },
    {
        id: 27,
        nombre: "Vestido Sevillana ",
        precio: 21,
        img: "/imgRebajas/rebaja8.png",
        cantidad: 1,
    
    },
    
    {
        id: 29,
        nombre: "Jersey Hilo",
        precio: 27,
        img: "/imgRebajas/rebaja10.png",
        cantidad: 1,
    
    }, 
];