const productos  = [
    {   id: 20,
        nombre: "REBAJAS", 
        precio: 100,
        img: "/img/zapatos.jpg",
        cantidad: 1,
    },
    {
        id: 21,
        nombre: "REBAJAS",
        precio: 50,
        img: "/img/pantalon.jpg",
        cantidad: 1,
    
    },
    {   id: 22,
        nombre: "REBAJAS", 
        precio: 100,
        img: "/img/zapatos.jpg",
        cantidad: 1,
    },
    {
        id: 23,
        nombre: "REBAJAS",
        precio: 50,
        img: "/img/pantalon.jpg",
        cantidad: 1,
    
    },
    {   id: 24,
        nombre: "REBAJAS", 
        precio: 100,
        img: "/img/zapatos.jpg",
        cantidad: 1,
    },
    {
        id: 25,
        nombre: "REBAJAS",
        precio: 50,
        img: "/img/pantalon.jpg",
        cantidad: 1,
    
    },
    {   id: 26,
        nombre: "REBAJAS", 
        precio: 100,
        img: "/img/zapatos.jpg",
        cantidad: 1,
    },
    {
        id: 27,
        nombre: "REBAJAS",
        precio: 50,
        img: "/img/pantalon.jpg",
        cantidad: 1,
    
    },
    {   id: 28,
        nombre: "REBAJAS", 
        precio: 100,
        img: "/img/zapatos.jpg",
        cantidad: 1,
    },
    {
        id: 29,
        nombre: "REBAJAS",
        precio: 50,
        img: "/img/pantalon.jpg",
        cantidad: 1,
    
    },
    {   id: 30,
        nombre: "REBAJAS", 
        precio: 100,
        img: "/img/zapatos.jpg",
        cantidad: 1,
    },    
];